[project]
name = "vulnerability-report"
version = "0.1.0"
description = "Produces 'suspect license' report"
authors = [
    { name = "Couchbase Build Team", email = "build-team@couchbase.com" }
]
# May as well use the same python version as the other tools, even though this
# particular one doesn't require the `blackduck` package
requires-python = ">=3.11, <3.12"
dependencies = [
    "requests",
    "python-dateutil>=2.8.0",
    "mdutils"
]
